from typing import Protocol

from app.documents.models import Document


class DocumentRepository(Protocol):
    async def add(self, document: Document) -> Document: ...
    async def get(self, document_id: int) -> Document | None: ...
    async def find_all(self) -> list[Document]: ...
    async def update(self, document: Document) -> Document: ...
    async def delete(self, document_id: int) -> bool: ...
