from typing import Protocol

from app.documents.models import Chunk, Document


class DocumentRepository(Protocol):
    async def add(self, document: Document) -> Document: ...
    async def get(self, document_id: int) -> Document | None: ...
    async def find_all(self) -> list[Document]: ...
    async def update(self, document: Document) -> Document: ...
    async def delete(self, document_id: int) -> bool: ...


class ChunkRepository(Protocol):
    async def add_many(self, chunks: list[Chunk]) -> list[Chunk]: ...
    async def find_by_document(self, document_id: int) -> list[Chunk]: ...
    async def delete_by_document(self, document_id: int) -> None: ...
